version: '3'

services:
  frontend:
    build: .
    ports:
      - 3000:3000
    command: /bin/sh -c "yarn serve"
    volumes:
      - .:/app:cached
      - frontend-node_modules:/app/node_modules
    tty: true
volumes:
  frontend-node_modules:
